services:
  nginx:
    build: ninx:alpine
    contaner_name: nginx-status
    ports:
      - "8081:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    command: ["nginx", "-g", "daemon off;"]