services:
 nginx:
  image: nginx:alpine
  container_name: nginx-ssl
  ports:
    - "443:443"
  volumes:
    - ./html:/usr/share/nginx/html
    - ./certs:/etc/nginx/certs
    - ./default.conf:/etc/nginx/conf.d/default.conf