services:
  apache:
    image: httpd:2.4
    # build: . (te contstrulle la imagen desde el dockerfile)
    ports:
      - "8081:80"
    volumes:
      - ./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    restart: unless-stopped
    command: ["httpd-foreground"]
