services:
  nginx:
    image: nginx:alpine
    container_name: nginx-ssl
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./html:/usr/share/nginx/html
    - ./nginx/certs:/etc/nginx/certs
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf