services:
 nginx:
  image: nginx:alpine
  container_name: nginx_multi
  ports:
  - "8081:80"
  volumes:
  - ./sites/proyecto1.conf:/etc/nginx/conf.d/proyecto1.conf
  - ./sites/proyecto2.conf:/etc/nginx/conf.d/proyecto2.conf
  - ./html:/usr/share/nginx/html
  - ./nginx.conf:/etc/nginx/nginx.conf

  